version: '3.9'

services:
  db:
    container_name: test_db
    env_file:
      - set.env
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createcachetable &&
             python manage.py runserver 0.0.0.0:3000"
    container_name: test_web
    depends_on:
      - db
    env_file:
      - set.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/code

volumes:
  postgres_data: