# Generated by Django 4.0.2 on 2022-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
