# Generated by Django 4.0.3 on 2022-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profilephoto_photo_articlecomms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComms',
            new_name='ArticleComments',
        ),
        migrations.AddField(
            model_name='profile',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
