# Generated by Django 4.0.3 on 2022-04-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_articlecomms_articlecomments_profile_raiting_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
