# Generated by Django 4.0.3 on 2022-04-20 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_room_messages_chat_remove_chat_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
